name: Daily Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Build
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE.CLOUDFLARE_BUILD_API }}" \
          -H "Content-Type: application/json"
