name: Daily Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Build
        env:
          CLOUDFLARE_BUILD_API: ${{ secrets.CLOUDFLARE.CLOUDFLARE_BUILD_API }}
        run: |
          curl -X POST "$CLOUDFLARE_BUILD_API" \
          -H "Content-Type: application/json"
